query GetMeetingsForUser($user_id: Int!, $email: String!, $date: date!) {
  createdMeetings: afrimeet_meetings(
    where: { creator: { _eq: $user_id }, date: { _gte: $date } }
  ) {
    meeting_id
    title
    date
    start_time
    end_time
    creator
    meetingroom {
      room_name
    }
    room_id
    participants {
      email
    }
    external_participants {
      name
    }
  }
  joinedMeetings: afrimeet_meetings(
    where: { participants: { email: { _eq: $email } }, date: { _gte: $date } }
  ) {
    meeting_id
    title
    date
    start_time
    end_time
    creator
    meetingroom {
      room_name
    }
    room_id
    participants {
      email
    }
    external_participants {
      name
    }
  }
}
