query GetMeetingId($date: date!, $startTime: String!, $endTime: String!) {
  meeting: afrimeet_meetings(
    where: {
      date: { _eq: $date },
      _or: [
        { start_time: { _lte: $startTime }, end_time: { _gte: $startTime } },
        { start_time: { _lte: $endTime }, end_time: { _gte: $endTime } },
        { start_time: { _lte: $startTime }, end_time: { _gte: $startTime } }
      ]
    }
  ) {
    meeting_id
  }
}
