query GetUpcomingMeetings($room_id: Int!, $current_time: String!, $date: date!) {
  meetings: afrimeet_meetings(
    where: {
      room_id: { _eq: $room_id }
      _or: [
        { date: { _gt: $date } }
        {
          _and: [
            { date: { _eq: $date } }
            {
              _or: [
                { start_time: { _gte: $current_time } }
                { end_time: { _gte: $current_time } }
              ]
            }
          ]
        }
      ]
    }
    order_by: { start_time: asc }
    limit: 3
  ) {
    meeting_id
    title
    start_time
    end_time
    creator
  }
}
