services:
  postgres:
    image: postgres:15
    container_name: pgdata
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - custom-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  hasura:
    image: hasura/graphql-engine:v2.36.1
    container_name: hasura
    restart: always
    ports:
      - ${HASURA_GRAPHQL_SERVER_PORT}:${HASURA_GRAPHQL_SERVER_PORT}
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    networks:
      - custom-network
    
  express:
    build: 
      context: .
      dockerfile: express.Dockerfile
    container_name: express
    restart: always
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
      
networks:
  custom-network:
    driver: bridge

volumes:
  pgdata:
