-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "afrimeet"."external_participants" add column "meeting_id" integer
--  not null;
