subscription GetRoomStatus($room_ids: [Int!], $date: date!) {
  rooms: afrimeet_meetings(
    where: {
      date: {_eq: $date}
      room_id: { _in: $room_ids }
    }
  ) {
    room_id
    start_time
    end_time
  }
}